version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ubuntu/app
    overwrite: yes

permissions:		⇐ https://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/reference-appspec-file-structure-permissions.html
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
        
hooks:			⇐ https://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
